name: "[DEV] CI/CD Notify API"

on:
  push:
    branches:
      - production

env:
  APP_NAME: bitsoft-notify
  APP_VERSION: "v1.0.0"
  NETWORK: nest-notify

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/${{ secrets.GHCR_USERNAME }}/${APP_NAME}:${APP_VERSION}
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/${APP_NAME}:${APP_VERSION}